#
# R. Demers 2022.
#
server:
  shutdown: graceful
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /api/error
#
management:
  endpoints:
    web:
      exposure:
        include: health
#
spring:
  main:
    cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 45s
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
#
org:
  rd:
    tmpl:
      snv:
        secret: the.beautiful.secret.key.to.change
        expiration: 30000
        authorities: snv.roles
#